"use client";
import {
  HiOutlineChatBubbleLeftRight,
  HiOutlineSpeakerWave,
  HiOutlineUserGroup,
  HiOutlineShieldCheck,
  HiOutlineCpuChip,
  HiOutlineLink,
  HiOutlineTableCells,
  HiOutlineSparkles,
  HiOutlineChartBar,
  HiOutlineBolt,
  HiOutlineGlobeAlt,
  HiOutlineDevicePhoneMobile,
  HiOutlineBuildingOffice2,
  HiOutlineAcademicCap,
  HiOutlineHeart,
  HiOutlineShoppingCart,
  HiOutlineCurrencyDollar,
  HiOutlineMapPin,
  HiOutlinePencilSquare,
  HiOutlineWrenchScrewdriver,
  HiOutlineBookOpen,
  HiOutlineCalculator,
  HiOutlineCalendarDays,
  HiOutlineQrCode,
  HiOutlineNewspaper,
  HiOutlineFlag,
  HiOutlineUsers,
  HiOutlineEnvelope,
  HiOutlinePlay,
  HiOutlinePhoto,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";
import {
  FaWhatsapp,
  FaInstagram,
  FaFacebookMessenger,
  FaSms,
} from "react-icons/fa";
import { MdOutlineContactPhone, MdOutlineCampaign } from "react-icons/md";
// import { TbBrandTelegram, TbMessageCircle2 } from "react-icons/tb";
import { TiMessages } from "react-icons/ti";

import { RiAdvertisementLine } from "react-icons/ri";

const iconMap = {
  communicate: HiOutlineChatBubbleLeftRight,
  advertise: RiAdvertisementLine,
  personalize: HiOutlineSparkles,
  agentAssist: MdOutlineContactPhone,
  security: HiOutlineShieldCheck,
  convBuilder: HiOutlineCpuChip,
  aiCopilot: HiOutlineBolt,
  integrations: HiOutlineLink,
  campaign: MdOutlineCampaign,
  whatsapp: FaWhatsapp,
  sms: HiOutlineDevicePhoneMobile,
  email: HiOutlineEnvelope,
  rcs: TiMessages ,
  instagram: FaInstagram,
  facebook: FaFacebookMessenger,
  voice: HiOutlineSpeakerWave,
  webchat: TiMessages,
  salesAgent: HiOutlineCurrencyDollar,
  supportAgent: HiOutlineUserGroup,
  marketingAgent: MdOutlineCampaign,
  commerceAgent: HiOutlineShoppingCart,
  analytics: HiOutlineChartBar,
  finance: HiOutlineCurrencyDollar,
  retail: HiOutlineShoppingCart,
  food: HiOutlineGlobeAlt,
  realestate: HiOutlineBuildingOffice2,
  health: HiOutlineHeart,
  travel: HiOutlineMapPin,
  education: HiOutlineAcademicCap,
  marketing: MdOutlineCampaign,
  sales: HiOutlinePencilSquare,
  support: HiOutlineChatBubbleLeftRight,
  product: HiOutlineWrenchScrewdriver,
  blog: HiOutlineNewspaper,
  docs: HiOutlineBookOpen,
  guides: HiOutlineBookOpen,
  roi: HiOutlineCalculator,
  events: HiOutlineCalendarDays,
  whatsappWidget: FaWhatsapp,
  ebooks: HiOutlineBookOpen,
  qr: HiOutlineQrCode,
  about: HiOutlineFlag,
  news: HiOutlineNewspaper,
  alliances: HiOutlineUsers,
  logo: HiOutlineChatBubbleLeftRight,
  play: HiOutlinePlay,
  cloud: HiOutlineRocketLaunch,
};

export default function NavIcon({ name, size = 20, className = "" }) {
  const Icon = iconMap[name] || HiOutlineGlobeAlt;
  return <Icon size={size} className={className} />;
}